# Generated by Django 5.2.4 on 2025-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_film_thumbnail_high_url_film_thumbnail_medium_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='playlist_order',
            field=models.IntegerField(blank=True, help_text='Order in YouTube playlist', null=True),
        ),
    ]
