# Generated by Django 5.2.4 on 2025-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_film_playlist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL for this chapter'),
        ),
    ]
