# Generated by Django 5.2.4 on 2025-07-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_chapter_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='has_years_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='years',
            field=models.CharField(blank=True, help_text='Years when this chapter was filmed', max_length=100),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['years'], name='main_chapte_years_30a927_idx'),
        ),
    ]
