# Generated by Django 5.2.4 on 2025-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_increase_person_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='youtube_id',
            field=models.CharField(help_text='YouTube video ID for embedding', max_length=50, unique=True),
        ),
    ]
