# Generated by Django 5.2.4 on 2025-07-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_increase_youtube_id_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
