-- SQL script to update chapter thumbnail URLs in production
-- Generated from local database after running update_chapter_thumbnails management command
-- Total updates: 285

BEGIN;

UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-61_FROS - Childrens Fairyland Christmas Disneyland Yosemite with Wrens and Myre relatives_image_000.jpg' WHERE id = 585;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-61_FROS - Childrens Fairyland Christmas Disneyland Yosemite with Wrens and Myre relatives_image_001.jpg' WHERE id = 586;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-61_FROS - Childrens Fairyland Christmas Disneyland Yosemite with Wrens and Myre relatives_image_002.jpg' WHERE id = 587;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-61_FROS - Childrens Fairyland Christmas Disneyland Yosemite with Wrens and Myre relatives_image_003.jpg' WHERE id = 588;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-61_FROS - Childrens Fairyland Christmas Disneyland Yosemite with Wrens and Myre relatives_image_004.jpg' WHERE id = 589;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-61_FROS - Childrens Fairyland Christmas Disneyland Yosemite with Wrens and Myre relatives_image_005.jpg' WHERE id = 590;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/62-SF_FROS - 1962 Seattle Worlds Fair_image_000.jpg' WHERE id = 434;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_000.jpg' WHERE id = 645;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_001.jpg' WHERE id = 646;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_002.jpg' WHERE id = 647;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_003.jpg' WHERE id = 648;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_004.jpg' WHERE id = 649;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_005.jpg' WHERE id = 650;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_006.jpg' WHERE id = 651;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_007.jpg' WHERE id = 652;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_008.jpg' WHERE id = 653;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_009.jpg' WHERE id = 654;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_010.jpg' WHERE id = 655;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_011.jpg' WHERE id = 656;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_012.jpg' WHERE id = 657;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_013.jpg' WHERE id = 658;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_014.jpg' WHERE id = 659;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_015.jpg' WHERE id = 660;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_016.jpg' WHERE id = 661;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_017.jpg' WHERE id = 662;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-03_FROS - Earl Hayward shot film of his wife Rosabell his children Marjorie Mary-Louise and John Sr and their families_image_018.jpg' WHERE id = 663;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-53_FROS - Bob Lindner Film 1 - Rock City Georgia Unknown People_image_000.jpg' WHERE id = 487;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-53_FROS - Bob Lindner Film 1 - Rock City Georgia Unknown People_image_001.jpg' WHERE id = 488;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-53_FROS - Bob Lindner Film 1 - Rock City Georgia Unknown People_image_002.jpg' WHERE id = 489;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-53_FROS - Bob Lindner Film 1 - Rock City Georgia Unknown People_image_003.jpg' WHERE id = 490;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-65_FROS - Bob Lindner Film 10 - Kids Summer Bible School Flower Garden_image_000.jpg' WHERE id = 510;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-65_FROS - Bob Lindner Film 10 - Kids Summer Bible School Flower Garden_image_001.jpg' WHERE id = 511;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-65_FROS - Bob Lindner Film 10 - Kids Summer Bible School Flower Garden_image_002.jpg' WHERE id = 512;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55A_FROS - Bob Lindner Film 2 - House Fire Boat Trip Locks_image_000.jpg' WHERE id = 491;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55A_FROS - Bob Lindner Film 2 - House Fire Boat Trip Locks_image_001.jpg' WHERE id = 492;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55A_FROS - Bob Lindner Film 2 - House Fire Boat Trip Locks_image_002.jpg' WHERE id = 493;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55A_FROS - Bob Lindner Film 2 - House Fire Boat Trip Locks_image_003.jpg' WHERE id = 494;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55A_FROS - Bob Lindner Film 2 - House Fire Boat Trip Locks_image_004.jpg' WHERE id = 495;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55A_FROS - Bob Lindner Film 2 - House Fire Boat Trip Locks_image_005.jpg' WHERE id = 496;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55B_FROS - Bob Lindner Film 3 - Parade_image_000.jpg' WHERE id = 497;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55C_FROS - Bob Lindner Film 4 - Train and Lindners with Earl and Rosabell_image_000.jpg' WHERE id = 498;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-55C_FROS - Bob Lindner Film 4 - Train and Lindners with Earl and Rosabell_image_001.jpg' WHERE id = 499;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-56A_FROS - Bob Lindner Film 5 - Niagra Falls_image_000.jpg' WHERE id = 500;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-56B_FROS - Bob Lindner Film 6 - Damaged Film of Cars Boat Park_image_000.jpg' WHERE id = 501;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-58_FROS - Bob Lindner Film 7 - Michigan Swans Farming Cypress Gardens_image_000.jpg' WHERE id = 502;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-58_FROS - Bob Lindner Film 7 - Michigan Swans Farming Cypress Gardens_image_001.jpg' WHERE id = 503;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-58_FROS - Bob Lindner Film 7 - Michigan Swans Farming Cypress Gardens_image_002.jpg' WHERE id = 504;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-58_FROS - Bob Lindner Film 7 - Michigan Swans Farming Cypress Gardens_image_003.jpg' WHERE id = 505;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-59_FROS - Bob Lindner Film 8 - Parade_image_000.jpg' WHERE id = 506;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-63_FROS - Bob Lindner Film 9 - Unknown People Baseball Game Squirrel_image_000.jpg' WHERE id = 507;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-63_FROS - Bob Lindner Film 9 - Unknown People Baseball Game Squirrel_image_001.jpg' WHERE id = 508;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-63_FROS - Bob Lindner Film 9 - Unknown People Baseball Game Squirrel_image_002.jpg' WHERE id = 509;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_000.jpg' WHERE id = 620;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_001.jpg' WHERE id = 621;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_002.jpg' WHERE id = 622;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_003.jpg' WHERE id = 623;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_004.jpg' WHERE id = 624;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_005.jpg' WHERE id = 625;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_006.jpg' WHERE id = 626;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_007.jpg' WHERE id = 627;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_008.jpg' WHERE id = 628;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_009.jpg' WHERE id = 629;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-01_FROS - Kids Christmas 1950, 51, and 52 both Hayward and Myers Grandparents aunths uncles and cousins_image_010.jpg' WHERE id = 630;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-56_FROS - Disney Trip with Irwin Wren and family_image_000.jpg' WHERE id = 577;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-56_FROS - Disney Trip with Irwin Wren and family_image_001.jpg' WHERE id = 578;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_000.jpg' WHERE id = 722;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_001.jpg' WHERE id = 723;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_002.jpg' WHERE id = 724;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_003.jpg' WHERE id = 725;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_004.jpg' WHERE id = 726;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_005.jpg' WHERE id = 727;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_006.jpg' WHERE id = 728;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-14_FROS - Marineland Disneyland Knotts Hearst Castle Hume Cabin Construction_image_007.jpg' WHERE id = 729;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_000.jpg' WHERE id = 591;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_001.jpg' WHERE id = 592;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_002.jpg' WHERE id = 593;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_003.jpg' WHERE id = 594;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_004.jpg' WHERE id = 595;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_005.jpg' WHERE id = 596;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_006.jpg' WHERE id = 597;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_007.jpg' WHERE id = 598;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_008.jpg' WHERE id = 599;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_009.jpg' WHERE id = 600;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_010.jpg' WHERE id = 601;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-CC1_FROS - Skiing Car Fire Josephine Twins and Earl and Rosabell Hawyard Bob-Marjorie-Lindner David-Gloria-Myre Great Lakes_image_011.jpg' WHERE id = 602;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_000.jpg' WHERE id = 416;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_001.jpg' WHERE id = 417;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_002.jpg' WHERE id = 418;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_003.jpg' WHERE id = 419;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_004.jpg' WHERE id = 420;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_005.jpg' WHERE id = 421;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_006.jpg' WHERE id = 422;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_007.jpg' WHERE id = 423;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_008.jpg' WHERE id = 424;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_009.jpg' WHERE id = 425;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_010.jpg' WHERE id = 426;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_011.jpg' WHERE id = 427;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_012.jpg' WHERE id = 428;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_013.jpg' WHERE id = 429;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_014.jpg' WHERE id = 430;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_015.jpg' WHERE id = 431;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_016.jpg' WHERE id = 432;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/59-HI_FROS - Hawaii Trip_image_017.jpg' WHERE id = 433;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_000.jpg' WHERE id = 454;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_001.jpg' WHERE id = 455;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_002.jpg' WHERE id = 456;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_003.jpg' WHERE id = 457;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_004.jpg' WHERE id = 458;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_005.jpg' WHERE id = 459;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_006.jpg' WHERE id = 460;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_007.jpg' WHERE id = 461;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_008.jpg' WHERE id = 462;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_009.jpg' WHERE id = 463;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_010.jpg' WHERE id = 464;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_011.jpg' WHERE id = 465;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_012.jpg' WHERE id = 466;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_013.jpg' WHERE id = 467;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_014.jpg' WHERE id = 468;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_015.jpg' WHERE id = 469;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_016.jpg' WHERE id = 470;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_017.jpg' WHERE id = 471;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_018.jpg' WHERE id = 472;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_019.jpg' WHERE id = 473;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_020.jpg' WHERE id = 474;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_021.jpg' WHERE id = 475;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_022.jpg' WHERE id = 476;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/HR-1-4_FROS - Multiple Reels Mostly Haywards Myres and Wrens Victoria BC Knotts Berry Farm Tubing Christmas Rose Parade Santas Village_image_023.jpg' WHERE id = 477;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-07_FROS - Parade Wagon Yosemite Dennis the Menace Park SF Bay Area_image_000.jpg' WHERE id = 707;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-07_FROS - Parade Wagon Yosemite Dennis the Menace Park SF Bay Area_image_001.jpg' WHERE id = 708;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-07_FROS - Parade Wagon Yosemite Dennis the Menace Park SF Bay Area_image_002.jpg' WHERE id = 709;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-07_FROS - Parade Wagon Yosemite Dennis the Menace Park SF Bay Area_image_003.jpg' WHERE id = 710;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-07_FROS - Parade Wagon Yosemite Dennis the Menace Park SF Bay Area_image_004.jpg' WHERE id = 711;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-07_FROS - Parade Wagon Yosemite Dennis the Menace Park SF Bay Area_image_005.jpg' WHERE id = 712;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_000.jpg' WHERE id = 713;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_001.jpg' WHERE id = 714;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_002.jpg' WHERE id = 715;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_003.jpg' WHERE id = 716;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_004.jpg' WHERE id = 717;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_005.jpg' WHERE id = 718;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_006.jpg' WHERE id = 719;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_007.jpg' WHERE id = 720;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-08_FROS - Snow Tubing Santas Village Family Picnic Pool CA Roadtrip_image_008.jpg' WHERE id = 721;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_000.jpg' WHERE id = 513;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_001.jpg' WHERE id = 514;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_002.jpg' WHERE id = 515;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_003.jpg' WHERE id = 516;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_004.jpg' WHERE id = 517;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_005.jpg' WHERE id = 518;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_006.jpg' WHERE id = 519;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_007.jpg' WHERE id = 520;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_008.jpg' WHERE id = 521;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_009.jpg' WHERE id = 522;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_010.jpg' WHERE id = 523;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_011.jpg' WHERE id = 524;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_012.jpg' WHERE id = 525;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_013.jpg' WHERE id = 526;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_014.jpg' WHERE id = 527;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_015.jpg' WHERE id = 528;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_016.jpg' WHERE id = 529;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_017.jpg' WHERE id = 530;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_018.jpg' WHERE id = 531;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-02_FROS - Michigan and Seattle Trips with both Myre and Hayward Great Grandparents_image_019.jpg' WHERE id = 532;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_000.jpg' WHERE id = 688;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_001.jpg' WHERE id = 689;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_002.jpg' WHERE id = 690;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_003.jpg' WHERE id = 691;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_004.jpg' WHERE id = 692;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_005.jpg' WHERE id = 693;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_006.jpg' WHERE id = 694;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_007.jpg' WHERE id = 695;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_008.jpg' WHERE id = 696;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-05_FROS - Hume Lake Public Pool Death Valley Trip_image_009.jpg' WHERE id = 697;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_000.jpg' WHERE id = 730;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_001.jpg' WHERE id = 731;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_002.jpg' WHERE id = 732;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_003.jpg' WHERE id = 733;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_004.jpg' WHERE id = 734;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_005.jpg' WHERE id = 735;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_006.jpg' WHERE id = 736;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_007.jpg' WHERE id = 737;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_008.jpg' WHERE id = 738;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PBA-01_FROS - New Orleans Visit_image_009.jpg' WHERE id = 739;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_000.jpg' WHERE id = 674;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_001.jpg' WHERE id = 675;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_002.jpg' WHERE id = 676;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_003.jpg' WHERE id = 677;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_004.jpg' WHERE id = 678;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_005.jpg' WHERE id = 679;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_006.jpg' WHERE id = 680;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_007.jpg' WHERE id = 681;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_008.jpg' WHERE id = 682;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_009.jpg' WHERE id = 683;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_010.jpg' WHERE id = 684;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_011.jpg' WHERE id = 685;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_012.jpg' WHERE id = 686;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-04_FROS - Western Parks Rainbow Forest Grand Canyon Sequoia Yosemite Crater Lake_image_013.jpg' WHERE id = 687;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_000.jpg' WHERE id = 533;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_001.jpg' WHERE id = 534;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_002.jpg' WHERE id = 535;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_003.jpg' WHERE id = 536;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_004.jpg' WHERE id = 537;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_005.jpg' WHERE id = 538;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_006.jpg' WHERE id = 539;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_007.jpg' WHERE id = 540;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_008.jpg' WHERE id = 541;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_009.jpg' WHERE id = 542;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_010.jpg' WHERE id = 543;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_011.jpg' WHERE id = 544;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_012.jpg' WHERE id = 545;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_013.jpg' WHERE id = 546;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_014.jpg' WHERE id = 547;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_015.jpg' WHERE id = 548;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_016.jpg' WHERE id = 549;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_017.jpg' WHERE id = 550;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_018.jpg' WHERE id = 551;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_019.jpg' WHERE id = 552;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-09-11_FROS - Seattle and Canada trip with Haywards and Oscar Myre and Irwin Wrens families_image_020.jpg' WHERE id = 553;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_000.jpg' WHERE id = 567;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_001.jpg' WHERE id = 568;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_002.jpg' WHERE id = 569;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_003.jpg' WHERE id = 570;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_004.jpg' WHERE id = 571;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_005.jpg' WHERE id = 572;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_006.jpg' WHERE id = 573;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_007.jpg' WHERE id = 574;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_008.jpg' WHERE id = 575;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-53_FROS - New Orleans Zoo Cemetery Bayou Mardi Gras Floats visit with Earl and Rosabell Hayward_image_009.jpg' WHERE id = 576;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-52_FROS - Damaged Scenes John Sr Josephine Earl and Rosabell National Park_image_000.jpg' WHERE id = 484;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-52_FROS - Damaged Scenes John Sr Josephine Earl and Rosabell National Park_image_001.jpg' WHERE id = 485;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/L-52_FROS - Damaged Scenes John Sr Josephine Earl and Rosabell National Park_image_002.jpg' WHERE id = 486;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_000.jpg' WHERE id = 631;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_001.jpg' WHERE id = 632;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_002.jpg' WHERE id = 633;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_003.jpg' WHERE id = 634;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_004.jpg' WHERE id = 635;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_005.jpg' WHERE id = 636;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_006.jpg' WHERE id = 637;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_007.jpg' WHERE id = 638;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_008.jpg' WHERE id = 639;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_009.jpg' WHERE id = 640;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_010.jpg' WHERE id = 641;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_011.jpg' WHERE id = 642;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_012.jpg' WHERE id = 643;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PA-02_FROS - John Jr and Joy as Babies with Myers_image_013.jpg' WHERE id = 644;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_000.jpg' WHERE id = 386;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_001.jpg' WHERE id = 387;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_002.jpg' WHERE id = 388;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_003.jpg' WHERE id = 389;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_004.jpg' WHERE id = 390;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_005.jpg' WHERE id = 391;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_006.jpg' WHERE id = 392;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_007.jpg' WHERE id = 393;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/57-PT_FROS - Josephine Southwest Trip Grand Canyon Bryce Canyon Zion Calico Ghost Town_image_008.jpg' WHERE id = 394;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_000.jpg' WHERE id = 664;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_001.jpg' WHERE id = 665;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_002.jpg' WHERE id = 666;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_003.jpg' WHERE id = 667;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_004.jpg' WHERE id = 668;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_005.jpg' WHERE id = 669;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_006.jpg' WHERE id = 670;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_007.jpg' WHERE id = 671;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_008.jpg' WHERE id = 672;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/PB-01_FROS - Lake Ocean Christmas Mini Golf McDonalds Birthday_image_009.jpg' WHERE id = 673;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_000.jpg' WHERE id = 406;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_001.jpg' WHERE id = 407;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_002.jpg' WHERE id = 408;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_003.jpg' WHERE id = 409;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_004.jpg' WHERE id = 410;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_005.jpg' WHERE id = 411;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_006.jpg' WHERE id = 412;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_007.jpg' WHERE id = 413;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_008.jpg' WHERE id = 414;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/58-V2_FROS - Canada Road Trip Montana Victoria BC_image_009.jpg' WHERE id = 415;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/KO-1_FROS - Korean Trip John Sr Part 1_image_000.jpg' WHERE id = 478;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/KO-1_FROS - Korean Trip John Sr Part 1_image_001.jpg' WHERE id = 479;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/KO-1_FROS - Korean Trip John Sr Part 1_image_002.jpg' WHERE id = 480;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/KO-2_FROS - Korean Trip John Sr Part 2 and Return Trip_image_000.jpg' WHERE id = 481;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/KO-2_FROS - Korean Trip John Sr Part 2 and Return Trip_image_001.jpg' WHERE id = 482;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/KO-2_FROS - Korean Trip John Sr Part 2 and Return Trip_image_002.jpg' WHERE id = 483;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-60_FROS - Train Trip Earl and Rosabell Hayward 50th Aniv SF Trip_image_000.jpg' WHERE id = 579;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-60_FROS - Train Trip Earl and Rosabell Hayward 50th Aniv SF Trip_image_001.jpg' WHERE id = 580;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-60_FROS - Train Trip Earl and Rosabell Hayward 50th Aniv SF Trip_image_002.jpg' WHERE id = 581;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-60_FROS - Train Trip Earl and Rosabell Hayward 50th Aniv SF Trip_image_003.jpg' WHERE id = 582;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-60_FROS - Train Trip Earl and Rosabell Hayward 50th Aniv SF Trip_image_004.jpg' WHERE id = 583;
UPDATE main_chapter SET thumbnail_url = '/static/thumbnails/chapters/P-60_FROS - Train Trip Earl and Rosabell Hayward 50th Aniv SF Trip_image_005.jpg' WHERE id = 584;

COMMIT;
